version: '3'
services:
  books:
    build: ./books
    ports:
      - "8001:8001"

  readers:
    build: ./readers
    ports:
      - "8002:8002"

  orders:
    build: ./orders
    ports:
      - "8003:8003"
